# Generated by Django 4.1.4 on 2023-01-06 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPlacesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название места')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание места')),
                ('review', models.TextField(max_length=2048, verbose_name='Воспоминание о месте')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес места')),
                ('data_published_memory', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания воспоминания')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотографии с впечатлениями')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug воспоминания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_list', to=settings.AUTH_USER_MODEL, verbose_name='Автор воспоминания')),
            ],
            options={
                'verbose_name': 'Воспоминание',
                'verbose_name_plural': 'Воспоминания',
                'ordering': ['-data_published_memory'],
            },
        ),
    ]
